# Generated by Django 4.2.7 on 2024-03-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptions'),
        ('users', '0003_user_role'),
    ]

    operations = [
    ]
